name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LC_ALL: C.UTF-8
      TZ: UTC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OCaml and opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1
          cache: true

      - name: Prepare opam (disable sandbox in CI)
        run: |
          opam init -y --reinit --disable-sandboxing
          eval "$(opam env)"
          opam update

      - name: Install build dependencies
        run: |
          eval "$(opam env)"
          # Pull deps from opam files; add dune explicitly
          opam install . --deps-only -y
          opam install dune -y

      - name: Configure GeneWeb
        run: |
          eval "$(opam env)"
          # Generate build config and make rules
          ocaml ./configure.ml

      - name: Build GeneWeb (distrib or all)
        run: |
          eval "$(opam env)"
          set -e
          if make -n distrib >/dev/null 2>&1; then
            make clean distrib
          else
            make clean all
          fi
          chmod +x ./gw/gwd || true
          ls -la ./gw || true

      - name: Smoke test HTTP server
        run: |
          set -e
          eval "$(opam env)"
          ./gw/gwd -hd ./gw -bd ./bases -p 23179 -lang en > gwd.out 2>&1 &
          GWD_PID=$!
          sleep 4
          set +e
          CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/test/)
          if [ "$CODE" != "200" ]; then
            CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/base/)
          fi
          set -e
          if [ "$CODE" != "200" ]; then
            echo "Smoke check failed (HTTP $CODE). Tail of gwd.out:"
            tail -n 120 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          kill "$GWD_PID" 2>/dev/null || true

      - name: Golden validate
        run: |
          eval "$(opam env)"
          chmod +x ./scripts/golden/run_golden.sh || true
          bash ./scripts/golden/run_golden.sh validate

      - name: Upload golden diff on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: golden-diff
          path: tests/golden/reports/diff.txt
          if-no-files-found: ignore
