name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    env:
      LC_ALL: C.UTF-8
      TZ: UTC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make executables
        run: |
          chmod +x GeneWeb/gw/* || true
          chmod +x scripts/golden/run_golden.sh || true

      - name: Smoke test gwd
        working-directory: GeneWeb
        run: |
          set -e
          ./gw/gwd -hd ./gw -bd ./bases -p 23179 -lang en > gwd.out 2>&1 &
          GWD_PID=$!
          sleep 3
          # Quick smoke: just verify gwd is serving (golden tests will do full validation)
          set +e
          CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/test)
          if [ "$CODE" != "200" ]; then
            CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/base)
          fi
          set -e
          # Accept server up if not 5xx/000
          if [ "$CODE" = "000" ] || [ "$CODE" -ge 500 ]; then
            echo "Smoke check failed (HTTP $CODE). Tail of gwd.out:"
            tail -n 100 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          # Determine base URL for content checks
          URL=http://localhost:23179/test
          if [ "$CODE" != "200" ]; then URL=http://localhost:23179/base; fi
          # Home page contains marker
          curl -sf "$URL" | grep -qi "geneweb" || { echo "Marker not found on home"; tail -n 100 gwd.out; kill "$GWD_PID" 2>/dev/null || true; exit 1; }
          # Person page (Charles Windsor): 200 + key markers
          PERSON_URL="${URL}?p=Charles&n=Windsor"
          if ! curl -sf "$PERSON_URL" | grep -qiE "name|person|id"; then
            echo "Person page markers missing on $PERSON_URL"
            tail -n 100 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          echo "Person page check passed"
          # FR Localization: Check French text appears when lang=fr
          FR_URL="${URL}?lang=fr"
          if ! curl -sf "$FR_URL" | grep -qiE "Accueil|Personne|Famille"; then
            echo "FR localization check failed on $FR_URL"
            tail -n 100 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          echo "FR localization check passed"
          # Logging: Check gwd.log exists and has no critical errors
          if [ ! -f gwd.out ]; then
            echo "Logging check failed: gwd.out not found"
            exit 1
          fi
          if grep -qiE "fatal|exception|stack" gwd.out; then
            echo "Logging check failed: critical errors found in gwd.out"
            grep -iE "fatal|exception|stack" gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          echo "Logging check passed (no critical errors)"
          # Note: Tree and search pages require Sosa reference configuration (via gwsetup)
          # which is not part of the minimal test database. Skipping these checks in CI.
          # Golden tests already validate core rendering behavior.
          echo "gwd smoke check passed (HTTP $CODE)"
          kill "$GWD_PID" 2>/dev/null || true

      - name: Export GEDCOM test
        working-directory: GeneWeb
        run: |
          set -e
          # Export GEDCOM from test.gwb (or base.gwb if test doesn't exist)
          if [ -d bases/test.gwb ]; then
            BASE_PATH="bases/test.gwb"
          elif [ -d bases/base.gwb ]; then
            BASE_PATH="bases/base.gwb"
          else
            echo "Export check failed: no test.gwb or base.gwb found"
            exit 1
          fi
          # Run gwb2ged export
          ./gw/gwb2ged "$BASE_PATH" -o /tmp/export_test.ged
          # Check file exists and has content
          if [ ! -f /tmp/export_test.ged ]; then
            echo "Export check failed: output file not created"
            exit 1
          fi
          FILE_SIZE=$(wc -c < /tmp/export_test.ged)
          if [ "$FILE_SIZE" -eq 0 ]; then
            echo "Export check failed: output file is empty"
            exit 1
          fi
          echo "Export check passed (file size: $FILE_SIZE bytes)"
          rm -f /tmp/export_test.ged

      - name: Golden validate (repo root)
        run: |
          chmod +x ./scripts/golden/run_golden.sh || true
          bash ./scripts/golden/run_golden.sh validate

      - name: Upload golden diff on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: golden-diff
          path: tests/golden/reports/diff.txt
          if-no-files-found: ignore
