name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    env:
      LC_ALL: C.UTF-8
      TZ: UTC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make executables
        run: |
          chmod +x GeneWeb/gw/* || true
          chmod +x scripts/golden/run_golden.sh || true

      - name: Smoke test gwd
        working-directory: GeneWeb
        run: |
          set -e
          ./gw/gwd -hd ./gw -bd ./bases -p 23179 -lang en > gwd.out 2>&1 &
          GWD_PID=$!
          sleep 3
          # Quick smoke: just verify gwd is serving (golden tests will do full validation)
          set +e
          CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/test)
          if [ "$CODE" != "200" ]; then
            CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/base)
          fi
          set -e
          # Accept server up if not 5xx/000
          if [ "$CODE" = "000" ] || [ "$CODE" -ge 500 ]; then
            echo "Smoke check failed (HTTP $CODE). Tail of gwd.out:"
            tail -n 100 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          # Determine base URL for content checks
          URL=http://localhost:23179/test
          if [ "$CODE" != "200" ]; then URL=http://localhost:23179/base; fi
          # Home page contains marker
          curl -sf "$URL" | grep -qi "geneweb" || { echo "Marker not found on home"; tail -n 100 gwd.out; kill "$GWD_PID" 2>/dev/null || true; exit 1; }
          # Person page (Charles Windsor): 200 + key markers
          PERSON_URL="${URL}?p=Charles&n=Windsor"
          if ! curl -sf "$PERSON_URL" | grep -qiE "name|person|id"; then
            echo "Person page markers missing on $PERSON_URL"
            tail -n 100 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          # Tree page (I1): assert HTTP 200 (template may warn about sosa_ref on some builds)
          TREE_URL="${URL}?m=TP&n=I1"
          TCODE=$(curl -s -o /dev/null -w "%{http_code}" "$TREE_URL")
          if [ "$TCODE" != "200" ]; then
            echo "Tree page HTTP check failed ($TCODE) on $TREE_URL"
            tail -n 100 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          echo "gwd smoke check passed (HTTP $CODE)"
          kill "$GWD_PID" 2>/dev/null || true

      - name: Golden validate (repo root)
        run: |
          chmod +x ./scripts/golden/run_golden.sh || true
          bash ./scripts/golden/run_golden.sh validate

      - name: Upload golden diff on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: golden-diff
          path: tests/golden/reports/diff.txt
          if-no-files-found: ignore
