name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    env:
      LC_ALL: C.UTF-8
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make executables
        run: |
          chmod +x GeneWeb/gw/* || true
          chmod +x scripts/golden/run_golden.sh || true

      - name: Integration smoke
        run: |
          set -e
          GeneWeb/gw/gwd -hd GeneWeb/gw -bd GeneWeb/bases -p 23179 -lang en > gwd.out 2>&1 &
          GWD_PID=$!
          sleep 3
          # Try /test/ then fallback to /base/, assert HTTP 200
          set +e
          CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/test/)
          if [ "$CODE" != "200" ]; then
            CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/base/)
          fi
          set -e
          if [ "$CODE" != "200" ]; then
            echo "Smoke check failed (HTTP $CODE). gwd output (last 80 lines):"
            tail -n 80 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          kill "$GWD_PID" 2>/dev/null || true

      - name: Golden validate
        run: bash scripts/golden/run_golden.sh validate

      - name: Upload golden diff (on failure)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: golden-diff
          path: tests/golden/reports/diff.txt
          if-no-files-found: ignore

