name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LC_ALL: C.UTF-8
      TZ: UTC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # OCaml + opam
      - name: Setup OCaml and opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.1.1
          cache: true

      - name: Prepare opam (disable sandboxing)
        run: |
          opam init -y --reinit --disable-sandboxing
          eval "$(opam env)"
          opam update

      - name: Locate GeneWeb root
        id: gwroot
        run: |
          set -e
          if [ -f "./configure.ml" ]; then
            echo "root=." >> $GITHUB_OUTPUT
          elif [ -f "GeneWeb/configure.ml" ]; then
            echo "root=GeneWeb" >> $GITHUB_OUTPUT
          else
            echo "::error::GeneWeb sources not found (./configure.ml or GeneWeb/configure.ml)."
            exit 1
          fi

      # Dépendances et build
      - name: Install deps
        run: |
          eval "$(opam env)"
          opam install dune -y
          opam install . --deps-only -y || true
        working-directory: ${{ steps.gwroot.outputs.root }}

      - name: Configure
        run: |
          eval "$(opam env)"
          ocaml ./configure.ml
        working-directory: ${{ steps.gwroot.outputs.root }}

      - name: Build
        run: |
          eval "$(opam env)"
          set -e
          if make -n distrib >/dev/null 2>&1; then
            make clean distrib
          else
            make clean all
          fi
          chmod +x ./gw/gwd || true
          ls -la ./gw || true
        working-directory: ${{ steps.gwroot.outputs.root }}

      - name: Smoke test gwd
        run: |
          set -e
          eval "$(opam env)"
          ./gw/gwd -hd ./gw -bd ./bases -p 23179 -lang en > gwd.out 2>&1 &
          GWD_PID=$!
          sleep 4
          set +e
          CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/test/ || true)
          if [ "$CODE" != "200" ]; then
            CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:23179/base/ || true)
          fi
          set -e
          if [ "$CODE" != "200" ]; then
            echo "Smoke failed (HTTP $CODE). Tail of gwd.out:"
            tail -n 120 gwd.out || true
            kill "$GWD_PID" 2>/dev/null || true
            exit 1
          fi
          kill "$GWD_PID" 2>/dev/null || true
        working-directory: ${{ steps.gwroot.outputs.root }}

      - name: Golden validate
        run: |
          chmod +x ./scripts/golden/run_golden.sh || true
          bash ./scripts/golden/run_golden.sh validate

      - name: Upload golden diff on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: golden-diff
          path: tests/golden/reports/diff.txt
          if-no-files-found: ignore
